package:
  name: extpackage
  version: 0.0.1
  top-level:
    - extpackage

source:
  path: source

about:
  home: https://github.com/rpwagner/pyodide-ext
  summary: A sample Python package
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - rpwagner
